### ISSUE TITLE
Great project! But I encountered some problems.

### ISSUE THREAD

**Issue by Byronnar** [askerlee/segtran#2]
When I train polyp datasets, the error occured, logs as before:
```
10 epochs, 1002 itertations each.
  0%|                                          | 0/10 [00:00<?, ?it/s]

Image scales: 8x8. Voxels: [1, 1600, 1792]
outputs shape: torch.Size([1, 2, 320, 320])
mask_batch shape: torch.Size([1, 3, 320, 320])
  0%|                                          | 0/10 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train2d.py", line 1100, in <module>
    mask_batch.permute([0, 2, 3, 1]))
  File "/root/anaconda3/envs/python377/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/python377/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 617, in forward
    reduction=self.reduction)
  File "/root/anaconda3/envs/python377/lib/python3.7/site-packages/torch/nn/functional.py", line 2433, in binary_cross_entropy_with_logits
    raise ValueError("Target size ({}) must be the same as input size ({})".format(target.size(), input.size()))
ValueError: Target size (torch.Size([1, 320, 320, 3])) must be the same as input size (torch.Size([1, 320, 320, 2]))
```
Could you tell me how to solve this problem? thank u!

**Comment by askerlee** [comment]
mask_batch shape: torch.Size([1, 3, 320, 320])
This means your masks have 3 channels, i.e., three segmentation classes. I hard-coded the polyp task to have 2 classes (according to my dataset). You can change 'num_classes' of 'polyp' to 3 to match your masks.

**Comment by Byronnar** [comment]
> mask_batch shape: torch.Size([1, 3, 320, 320])
> This means your masks have 3 channels, i.e., three segmentation classes. I hard-coded the polyp task to have 2 classes (according to my dataset). You can change 'num_classes' of 'polyp' to 3 to match your masks.

Thank you for your prompt reply！！！ OK

**Comment by Byronnar** [comment]
> mask_batch shape: torch.Size([1, 3, 320, 320])
> This means your masks have 3 channels, i.e., three segmentation classes. I hard-coded the polyp task to have 2 classes (according to my dataset). You can change 'num_classes' of 'polyp' to 3 to match your masks.

I have solved this problem, but I found there ar no inference scripts, just a test.py, can you give me a inference  python scripts? I want to vitualize the results, Thank you !

**Comment by askerlee** [comment]
Not sure what you mean by inference. test2d.py and test3d.py do inference on 2d and 3d datasets. Do you mean doing inference on a *single image* instead of a *dataset*?

**Comment by Byronnar** [comment]
> Not sure what you mean by inference. test2d.py and test3d.py do inference on 2d and 3d datasets. Do you mean doing inference on a _single image_ instead of a _dataset_?

Yeah~, test2d.py can only inference with datasets(datasets have labels), I want to doing inference on a single image instead of a dataset..

**Comment by askerlee** [comment]
Well it's easy 😁 (but a bit hacky) you can put the test images in a subfolder under the task data folder. Then add a dataset to test2d.py and set 'has_mask' as False.

**Comment by Byronnar** [comment]
> Well it's easy 😁 (but a bit hacky) you can put the test images in a subfolder under the task data folder. Then add a dataset to test2d.py and set 'has_mask' as False.

Thank you very much! I will try!

**Comment by Byronnar** [comment]
Mayby last question, I have trained a model, but hen I run test.py, there are some mistakes:
python test2d.py  --task polyp --split all --ds Kvasir-test --net segtran --translayers 3 --layercompress 1,1,2,2 --cpdir ../model/segtran-polyp-Kvasir-train-06190647 --iters 1500
```
0it [00:00, ?it/s]
Image scales: 8x8. Voxels: [8, 1600, 1792]
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "test2d.py", line 733, in <module>
    allcls_avg_metric = test_calculate_metric(iter_nums)
  File "test2d.py", line 686, in test_calculate_metric
    verbose=args.verbose_output)
  File "/home/projects/segtran/code/test_util2d.py", line 69, in test_all_cases
    batch_metric = calc_batch_metric(preds_soft, orig_mask_batch, num_classes, mask_thres)
  File "/home/projects/segtran/code/test_util2d.py", line 248, in calc_batch_metric
    C_pred_soft = F.interpolate(C_pred_soft.unsqueeze(0), size=C_gt.shape[1:], mode='bilinear', align_corners=False)
  File "/root/anaconda3/envs/python377/lib/python3.7/site-packages/torch/nn/functional.py", line 3013, in interpolate
    scale_factor_list[0], scale_factor_list[1])
RuntimeError: It is expected output_size equals to 2, but got size 1
```
How should I modify it?  Thank you!

**Comment by askerlee** [comment]
Did you put your own images in Kvasir-test? Looks like it's still because the number of classes is not set correctly. Have you tried to change this setting in test2d.py?

**Comment by askerlee** [comment]
Seems I should provide a command line argument to allow overriding the hardcoded number of classes 🤔

**Comment by Byronnar** [comment]
> Seems I should provide a command line argument to allow overriding the hardcoded number of classes 🤔

My dataset name is Kvasir-SEG,   it is  downloaded from https://datasets.simula.no/kvasir-seg/, number_classes should be 2, train is fine, bu inference....

**Comment by askerlee** [comment]
This is weird... I need to download the dataset and check. But currently I'm busy with other work. Will come back to this issue later.
