### ISSUE TITLE
about nnunet

### ISSUE THREAD

**Issue by Lemonweier** [askerlee/segtran#43]
Dear sir, we want to use the code of nnU-Net on fundus (2d images).  We have some problems, could you give us some guidance, thank u!
We also notice you have mentioned' It is primarily designed for 3D tasks, but can also handle 2D images after converting them to pseudo-3D.'
Here are our settings and traceback:
The parameter are `--nproc_per_node=1 --master_port=7152 /data/sementation/code/train2d.py --task fundus --ds train --split train --translayers 3 --layercompress 1,1,2,2 --net nnunet --bb resnet101 --maxiter 5000 --bs 32 --noqkbias`

`Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/root/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/root/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/data/sementation/code/train2d.py", line 1434, in <module>
    outputs = net(image_batch)
  File "/data/hliu/anaconda3/install/envs/segtran-master1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/hliu/anaconda3/install/envs/segtran-master1/lib/python3.8/site-packages/nnunet/network_architecture/generic_UNet.py", line 400, in forward
    x = torch.cat((x, skips[-(u + 1)]), dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 6 but got size 5 for tensor number 1 in the list.`

**Comment by askerlee** [comment]
Hi, thanks for using our code.
To use nnunet, the input image dimensions (H and W) haev to be divided by 64. Therefore, you need to set the image size to 256*256. To do so, just append `--patch 256` to your command line above 😃

**Comment by Lemonweier** [comment]
您发给我的邮件已收到，谢谢！

**Comment by Lemonweier** [comment]
Thank u, sir. It's a great honor to meet you on my way to code. Thank you for your patience 👍👍.

**Comment by askerlee** [comment]
You are very welcome. This is the least I can do.
